### ISSUE TITLE
Appimage file doesn't work on Linux mint 19.3 cinnamon.

### ISSUE THREAD

**Issue by qianyigengwu** [morevnaproject-org/opentoonz#36] opened 2020-03-25 08:18 UTC
update stuff
./../bin/OpenToonz: symbol lookup error: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: xcb_dri3_get_supported_modifiers

**Comment by morevnaproject** [comment] 2020-06-11 14:14
Duplicate of #29.

**Closed by morevnaproject** 2020-06-11 14:14 UTC
Labels: bug
